server:
  port: 10100
  servlet:
    context-path: /taskServer
spring:
  application:
    name: TASK-SERVER
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      register-with-eureka: true
      defaultZone: http://titan:df6100@172.20.100.29:7777/eureka/
logging:
  level:
    com.riozenc.task: debug
  path: log
