server:
  port: 6159
  servlet:
    context-path: /taskServer
spring:
  application:
    name: TASK-SERVER
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://titan:df6100@10.39.68.27:6150/eureka/
#      defaultZone: http://titan:df6100@172.20.100.29:7777/eureka/
logging:
  level:
    com.riozenc.task: debug
  path: log
